sudo: required
dist: trusty
language: generic

install:
  - sudo add-apt-repository -y ppa:beineri/opt-qt571-trusty
  - sudo apt-get update
  - sudo apt-get -y install -qq qt57-meta-full qt57charts-no-lgpl

script:
  - source /opt/qt57/bin/qt57-env.sh
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Release -DWITH_DEBIAN=ON
  - make -j4
